# HarvestMCP Configuration

harvest:
  client_id: "4npFjmvY_YXMzygxlyZA4KFG"
  client_secret: "YjQFZrEyxJFTzT-U1x0Dl9TsY0TDex8kmxW1JwYuUbxsh4BcXnu-Jzc2zkZ0UfTxTqnlNfD0TGlk-pIBedrGVw"
  redirect_uri: "http://localhost:8080/callback"
  token_path: "~/.harvest/token.json"
  authorize_url: "https://id.getharvest.com/oauth2/authorize"
  token_url: "https://id.getharvest.com/api/v2/oauth2/token"
  api_base_url: "https://api.harvestapp.com/v2"
  user_agent: "HarvestMCP (joakim.ekman@digitalist.se)"

forecast:
  client_id: "4npFjmvY_YXMzygxlyZA4KFG"
  client_secret: "YjQFZrEyxJFTzT-U1x0Dl9TsY0TDex8kmxW1JwYuUbxsh4BcXnu-Jzc2zkZ0UfTxTqnlNfD0TGlk-pIBedrGVw"
  redirect_uri: "http://localhost:8080/callback"
  token_path: "~/.harvest/forecast_token.json"
  authorize_url: "https://id.getharvest.com/oauth2/authorize"
  token_url: "https://id.getharvest.com/api/v2/oauth2/token"
  api_base_url: "https://api.forecastapp.com"
  user_agent: "HarvestMCP (joakim.ekman@digitalist.se)"
